version: '3.8'

services:
  hospital-backend:
    image: hosptial-hospital-backend:latest
    container_name: hospital-backend
    ports:
      - "8080:8080"
    environment:
      # Railway MySQL connection
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: YCrZjRPdipMRRfDyLoWNUCTxgJjgfUJU
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
